# lightning.pytorch==2.3.2
seed_everything: 0
trainer:
  accelerator: gpu
  devices: [0,1]
  # accelerator: auto
  # devices: auto
  strategy: ddp_find_unused_parameters_true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  max_epochs: 2
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
ckpt_path: null
model:
  class_path: models.Autoencoder
  init_args:
    num_ifos: 2
    num_timesteps: 200
    bottleneck: 8
data:
  class_path: dataloader.SineGaussianDataloader
  init_args:
    data_dir: /home/ethan.marx/aframe/data/train/background
    sample_rate: 2048
    kernel_length: 0.09765625
    psd_length: 64
    fduration: 1
    fftlength: 2
    batch_size: 128
    batches_per_epoch: 128
    num_workers: 5
    prior: gwak.data.prior.SineGaussianHighFrequency
    waveform: ml4gw.waveforms.SineGaussian
    init_args:
      sample_rate: 2048
      duration: 1.09765625