ifos: ["H1", "L1"]
# psd_length: 64
# fduration: 1
kernel_length: 0.09765625
kernel_length: 1
Tb: 1800
batch_size: 1
# stride_batch_size: 1
sample_rate: 2048
fname: /home/hongyin.chen/Data/GWAK_data/gwak_infer_data
data_foramt: hdf5
shifts: [0, 1]
project: white_noise_purst
model_repo_dir: /home/hongyin.chen/anti-gravity/gwak/gwak/output/export
image: hermes/tritonserver:23.01
result_dir: /home/hongyin.chen/anti-gravity/gwak/gwak/output/infer
load_model_patients: 25
inference_sampling_rate: 1
